# Generated by Django 4.2.4 on 2023-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('youtube_id', models.CharField(max_length=15)),
                ('start_time', models.PositiveIntegerField()),
                ('pre_sentence', models.TextField()),
                ('sentence', models.TextField()),
                ('post_sentence', models.TextField()),
            ],
        ),
    ]
